# Generated by Django 5.0.4 on 2024-04-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='photo',
        ),
    ]
