# Generated by Django 5.0.4 on 2024-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shoesize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=3, unique=True),
        ),
    ]
