# Generated by Django 5.0.4 on 2024-04-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_item_name_alter_shoesize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='clothing_size',
            field=models.ManyToManyField(blank=True, to='shop.clothingsize'),
        ),
    ]
