# Generated by Django 5.0.4 on 2024-04-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_clothing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='area_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
