# Generated by Django 5.0.4 on 2024-05-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_usercart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='items',
        ),
    ]
